// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "deployment/blob-storage.mdx": () => import("../content/docs/deployment/blob-storage.mdx?collection=docs"), "deployment/environment.mdx": () => import("../content/docs/deployment/environment.mdx?collection=docs"), "deployment/vercel.mdx": () => import("../content/docs/deployment/vercel.mdx?collection=docs"), "packages/agent.mdx": () => import("../content/docs/packages/agent.mdx?collection=docs"), "packages/auth.mdx": () => import("../content/docs/packages/auth.mdx?collection=docs"), "packages/chat.mdx": () => import("../content/docs/packages/chat.mdx?collection=docs"), "packages/code-editor.mdx": () => import("../content/docs/packages/code-editor.mdx?collection=docs"), "packages/convex.mdx": () => import("../content/docs/packages/convex.mdx?collection=docs"), "packages/database.mdx": () => import("../content/docs/packages/database.mdx?collection=docs"), "packages/error-manager.mdx": () => import("../content/docs/packages/error-manager.mdx?collection=docs"), "packages/integrations.mdx": () => import("../content/docs/packages/integrations.mdx?collection=docs"), "packages/payments.mdx": () => import("../content/docs/packages/payments.mdx?collection=docs"), "packages/prompt-engine.mdx": () => import("../content/docs/packages/prompt-engine.mdx?collection=docs"), "packages/publish.mdx": () => import("../content/docs/packages/publish.mdx?collection=docs"), "packages/pusher.mdx": () => import("../content/docs/packages/pusher.mdx?collection=docs"), "packages/remix.mdx": () => import("../content/docs/packages/remix.mdx?collection=docs"), "packages/restore.mdx": () => import("../content/docs/packages/restore.mdx?collection=docs"), "packages/sandbox.mdx": () => import("../content/docs/packages/sandbox.mdx?collection=docs"), "packages/starter-kit.mdx": () => import("../content/docs/packages/starter-kit.mdx?collection=docs"), "packages/ui.mdx": () => import("../content/docs/packages/ui.mdx?collection=docs"), "packages/visual-edits.mdx": () => import("../content/docs/packages/visual-edits.mdx?collection=docs"), }),
};
export default browserCollections;